export const cardsData = [
  {
    id: 1,
    title: "Plumbing",
    list: [
      "Install / Replace a Toilet",
      "Install / Replace a Faucet",
      "Fix a Leaking",
      "Install / Replace a Sink",
      "Repair Under Sink Plumbing",
    ],
    icon: "#icon-tap",
     color: "#179D2E",
  },
  {
    id: 2,
    title: "Drywall & painting",
    list: [
      "Install Drywall",
      "Patch and Paint Drywall",
      "Paint a Wall / Trim",
      "Paint or Stain A Fence",
      "Paint a Cabinet Door",
    ],
    icon: "#icon-paint",
    color: "#0177B8",
  },
  {
    id: 3,
    title: "Furniture assembly",
    list: [
      "Assemble Fitness Equipment",
      "Assemble - Custom Request",
      "Assemble a TV Stand",
      "Assemble Pet Furniture",
      "Assemble a Bar Cabinet",
    ],
    icon: "#icon-sofa",
    color: "#F5AF23",
  },
  {
    id: 4,
    title: "Electrical",
    list: [
      "Install / Replace a Ceiling Fan",
      "Replace Switch & Outlet Faceplate",
      "Upgrade to a Video Doorbell",
      "Install / Replace an Bathroom Exhaust Fan",
    ],
    icon: "#icon-electrical",
    color: "#F02E2C",
  },
  {
    id: 5,
    title: "Doors & windows",
    list: [
      "Install / Replace New Door",
      "Install / Replace a Screen Door",
      "Install / Replace a Window Screen",
      "Repair a Door Frame",
    ],
    icon: "#icon-door",
    color: "#179D2E",
  },
  {
    id: 6,
    title: "Hanging & mounting",
    list: [
      "Mount a TV",
      "Remove a TV Mount from Wall",
      "Mount and Hang a Projector Screen",
      "Hang a Bathroom Fixture",
    ],
    icon: "#icon-picture",
     color: "#0177B8",
  },
  {
    id: 7,
    title: "Appliance installation",
    list: [
      "Replace an Existing Dishwasher",
      "Replace an Existing Microwave",
      "Replace an Existing Oven",
    ],
    icon: "#icon-instalation",
    color: "#F5AF23",
  },
  {
    id: 8,
    title: "Smart home",
    list: [
      "Install a Smart Lock",
      "Install a Smart Home Security Camera",
      "Mount a Baby Monitor Camera on the Wall",
      "Install an Under Sink Water Filtration System",
    ],
    icon: "#icon-home",
     color: "#F02E2C",
  },
  {
    id: 9,
    title: "Outdoor",
    list: [
      " Assemble an Outdoor Trampoline",
      "Hang a Garage Shelving Unit",
      "Install Outdoor Decorative Exterior Window Shutters",
      "Install a Storm Door",
    ],
    icon: "#icon-outdoor",
    color: "#179D2E",
  },
];
